@file:Suppress("MagicNumber")
package roadfriend.app.uikit.compose.theme.color

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class TomColors(
    val hadiPrimary: Color,
    val hadiPrimaryLight: Color,
    val hadiLight: Color,
    val backgroundPrimary: Color,
    val backgroundSecondary: Color,
    val backgroundPrimaryComponent: Color,
    val backgroundSecondaryComponent: Color,
    val divider: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textPassive: Color,
    val textWhite: Color,
    val textPurple: Color,
    val textRed: Color,
    val neutral1: Color,
    val neutral2: Color,
    val neutral3: Color,
    val neutral4: Color,
    val neutral5: Color,
    val neutral6: Color,
    val neutral7: Color,
    val neutral8: Color,
    val neutral9: Color,
    val neutral10: Color,
    val yellow: Color,
    val yellow1: Color,
    val yellow2: Color,
    val yellow3: Color,
    val green: Color,
    val greenLight1: Color,
    val greenLight2: Color,
    val red: Color,
    val redLight1: Color,
    val redLight2: Color,
    val blue: Color,
    val blueLight1: Color,
    val blueLight2: Color,
    val orange: Color,
    val orangeLight1: Color,
    val orangeLight2: Color,
    val whitish: Color,
    val white: Color,
    val transparent: Color,
    val purple: Color,
    val black: Color
) {
    companion object {
        fun default(): TomColors = TomColors(
            hadiPrimary = Color(0xFF763AC7),
            hadiPrimaryLight = Color(0xFFA64FFF),
            hadiLight = Color(0xFFE4DAF1),
            backgroundPrimary = Color(0xFFF3F4F9),
            backgroundSecondary = Color(0xFFF1F3F5),
            backgroundPrimaryComponent = Color(0xFFFFFFFF),
            backgroundSecondaryComponent = Color(0xFFF3F4F9),
            divider = Color(0xFFECEDF0),
            textPrimary = Color(0xFF343A40),
            textSecondary = Color(0xFF70798C),
            textPassive = Color(0xFFD0D3DA),
            textWhite = Color(0xFFFFFFFF),
            textPurple = Color(0xFF763AC7),
            textRed = Color(0xFFFF3C2B),
            neutral1 = Color(0xFFFFFFFF),
            neutral2 = Color(0xFFF3F4F9),
            neutral3 = Color(0xFFECEDF0),
            neutral4 = Color(0xFFE5E7EB),
            neutral5 = Color(0xFFD0D3DA),
            neutral6 = Color(0xFFBFC4CD),
            neutral7 = Color(0xFF70798C),
            neutral8 = Color(0xFF343A40),
            neutral9 = Color(0xFF191E25),
            neutral10 = Color(0xFF15151A),
            yellow = Color(0xFFFFCD2B),
            yellow1 = Color(0xFFFFE07D),
            yellow2 = Color(0xFFFFF2C8),
            yellow3 = Color(0xFFFFFDF5),
            green = Color(0xFF40B72C),
            greenLight1 = Color(0xFFA9D998),
            greenLight2 = Color(0xFFDEF1D7),
            red = Color(0xFFFF3C2B),
            redLight1 = Color(0xFFFF978E),
            redLight2 = Color(0xFFFFDAD7),
            blue = Color(0xFF1562F5),
            blueLight1 = Color(0xFF83ADFF),
            blueLight2 = Color(0xFFDBE7FF),
            orange = Color(0xFFFF7C2F),
            orangeLight1 = Color(0xFFFFA774),
            orangeLight2 = Color(0xFFFFD6BF),
            whitish = Color(0xFFF1F3F5),
            white = Color(0xFFFFFFFF),
            transparent = Color(0x00000000),
            purple = Color(0xFF763AC7),
            black = Color(0xFF000000)
        )
    }
}
